# Generated by Django 5.1.6 on 2025-02-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='macroevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('short_description', models.TextField(verbose_name='Short Description(max: 150 char)')),
                ('long_description', models.TextField(verbose_name='Detailed Description')),
            ],
        ),
    ]
