# Generated by Django 5.1.6 on 2025-02-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='macroevents',
            new_name='macroevent',
        ),
    ]
