# Generated by Django 5.1.6 on 2025-03-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_macroevents_macroevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroevent',
            name='is_banner',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
