# Generated by Django 5.1.6 on 2025-03-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_department_association_name'),
        ('core', '0003_macroevent_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='microevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('short_description', models.TextField(verbose_name='Short Description(max: 150 char/card)')),
                ('long_description', models.TextField(verbose_name='Detailed Description')),
                ('round_details', models.TextField(verbose_name='Round details(Point wise desc. delimiter:\\n)')),
                ('jury_details', models.TextField()),
                ('event_venue', models.TextField(max_length=100)),
                ('maximum_participation', models.IntegerField(verbose_name='Maximum Individuals')),
                ('is_team_event', models.BooleanField()),
                ('min_team_size', models.IntegerField()),
                ('max_team_size', models.IntegerField()),
                ('registration_closed', models.BooleanField()),
                ('student_coordinator', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('micro_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.macroevent')),
            ],
        ),
    ]
