# Generated by Django 5.1.6 on 2025-03-01 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_microevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField()),
                ('macroevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.macroevent')),
                ('microevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microevent')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teammember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('attendance', models.BooleanField()),
                ('is_registrar', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microevent')),
                ('macroevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.macroevent')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
            ],
        ),
    ]
