# Generated by Django 5.1.6 on 2025-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='microevent',
            name='poster',
            field=models.FileField(default='nil', upload_to=''),
            preserve_default=False,
        ),
    ]
