# Generated by Django 5.1.6 on 2025-03-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_microevent_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microevent',
            name='poster',
            field=models.FileField(upload_to='posters'),
        ),
    ]
