# Generated by Django 5.1.6 on 2025-03-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submission_timestamp_teammember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_question',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.macroevent'),
        ),
    ]
