# Generated by Django 5.1.6 on 2025-03-08 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_review_question_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='microevent',
            name='additional_files',
            field=models.FileField(blank=True, null=True, upload_to='additional_files'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='attendancemoderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
