# Generated by Django 5.1.6 on 2025-03-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_microevent_additional_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microevent',
            name='ad_btn_text',
            field=models.CharField(default='Download', max_length=30, verbose_name='Button Text'),
            preserve_default=False,
        ),
    ]
