# Generated by Django 5.1.6 on 2025-03-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_microevent_ad_btn_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microevent',
            name='ad_btn_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Button Text'),
        ),
    ]
