# Generated by Django 5.1.6 on 2025-02-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_personalmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personalmail',
            new_name='collegemail',
        ),
    ]
