# Generated by Django 5.1.6 on 2025-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_personalmail_user_collegemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='association_name',
            field=models.CharField(default='Example', max_length=100),
            preserve_default=False,
        ),
    ]
