# Generated by Django 5.1.6 on 2025-03-01 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='stream_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.stream'),
        ),
    ]
