# Generated by Django 5.1.6 on 2025-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_department_stream_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_pseudo',
            field=models.CharField(default='CSE', max_length=10),
            preserve_default=False,
        ),
    ]
