# Generated by Django 5.1.6 on 2025-03-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_department_dept_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='stream_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.stream'),
        ),
    ]
